### Enroll in a course
POST http://localhost:3000/enrollment/{{courseId}}/enroll
Authorization: Bearer {{token}}

###

### Get student's dashboard
GET http://localhost:3000/enrollment/me/dashboard
Authorization: Bearer {{token}}

###

### Unenroll from a course
DELETE http://localhost:3000/enrollment/{{courseId}}/unenroll
Authorization: Bearer {{token}}
