@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYzY2MTdhOS01NjM3LTRiZTgtOTc3OS1lMDJkNzZlZDQyNTIiLCJlbWFpbCI6Imluc3RydWN0b3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTY5OTgyNywiZXhwIjoxNzUxNzg2MjI3fQ.iOTPlgOMEx_-27WI_LNzAq7ilbbU_5PrgV7PzFEQ8cU


### 📘 Create Content (Instructor Only)
POST http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Module 1: Introduction to NestJS",
  "order": 2
}

###

### 📗 Get All Content for Course
GET http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents
Authorization: Bearer {{instructor_token}}

###

### 🛠️ Update Content
PATCH http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents/e0e171af-f619-48ea-baa3-8db12d6f212c
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Updated Module 1 Title",
  "order": 2
}

###

### ❌ Delete Content
DELETE http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents/d889ea9a-a62d-4a48-aac2-49c53f5748aa
Authorization: Bearer {{instructor_token}}


