@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjhmYWFmNS1hMmMyLTRhNGQtYWE3YS02MWJmNmM3ZWVlMTIiLCJlbWFpbCI6Imluc3RydWN0b3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTkxOTg2MiwiZXhwIjoxNzUyMDA2MjYyfQ.RrySldNoBkXXuqNzg5euj4AAO3QnCdScvFJSJMAeLGI


### 📘 Create Content (Instructor Only)
POST http://localhost:3000/courses/5103ef6a-375f-4752-97c9-b57b76a65639/contents
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Module 2: Introduction to Spanish Greetings",
  "order": 3
}

###

### 📗 Get All Content for Course
GET http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents
Authorization: Bearer {{instructor_token}}

###

### 🛠️ Update Content
PATCH http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents/e0e171af-f619-48ea-baa3-8db12d6f212c
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Updated Module 1 Title",
  "order": 2
}

###

### ❌ Delete Content
DELETE http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb/contents/d889ea9a-a62d-4a48-aac2-49c53f5748aa
Authorization: Bearer {{instructor_token}}


