@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZTMzNTRlZS04ZWJjLTQ1MGYtYjBhNC04MGM0ZDM3YTljOWIiLCJlbWFpbCI6ImppbWphbUB3YWlnYW5qby5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTc0NjExMCwiZXhwIjoxNzUxODMyNTEwfQ.YKhPdNY20fiHsBxneL4gweXbw1YpiL3e7FhN4BaRUP8

###

### ✅ Create Course (Instructor Only)
POST http://localhost:3000/courses
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Tailwindcss intro",
  "description": "A complete intro course",
  "category": "Tailwind",
  "difficulty": "BEGINNER",
  "objectives": "learn Tailwind css",
  "prerequisites": "CSS",
  "image": "https://example.com/images/angular.png"
}

###

### 📥 Get All Published Courses (Public)
GET http://localhost:3000/courses

###

### 🧑‍🏫 Get My Courses (Instructor Only)
GET http://localhost:3000/courses/my
Authorization: Bearer {{instructor_token}}

###

### 📄 Get One Course by ID
GET http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb
Authorization: Bearer {{instructor_token}}

###

### ✏️ Update Course
PATCH http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "NestJS for Beginners - Updated",
  "published": true
}

###

### ❌ Delete Course
DELETE http://localhost:3000/courses/ab1f49df-8094-476b-9692-876ac0dce926
Authorization: Bearer {{instructor_token}}
