@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjY0YWI1YS1iNmY1LTRlMWItOGU0MS1iNjliNmFlYjMwODciLCJlbWFpbCI6Imhha2lteWFraW0yMDBAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxOTAxODA1LCJleHAiOjE3NTE5ODgyMDV9.anDGorVvvCd7quZ26rSpN8h1Ocq1h8v4utvynyxlWjY
@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYzY2MTdhOS01NjM3LTRiZTgtOTc3OS1lMDJkNzZlZDQyNTIiLCJlbWFpbCI6Imluc3RydWN0b3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTkwMjAxMiwiZXhwIjoxNzUxOTg4NDEyfQ.-lJRk10vykGbq-Z-cIVWFMMeZFnH-Yvu7vWUftg2Izo
###

### ✅ Create Course (Instructor Only)
POST http://localhost:3000/courses
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Biz",
  "description": "A complete intro course",
  "category": "Bo",
  "difficulty": "BEGINNER",
  "objectives": "Biz",
  "prerequisites": "Money",
  "image": "https://example.com/images/angular.png"
}

###

### 📥 Get All Published Courses (Public)
GET http://localhost:3000/courses

###

### 🧑‍🏫 Get My Courses (Instructor Only)
GET http://localhost:3000/courses/my
Authorization: Bearer {{instructor_token}}

###

### 📄 Get One Course by ID
GET http://localhost:3000/courses/888baab1-2c0b-4612-9d28-216927ba43dd
Authorization: Bearer {{instructor_token}}

###

### ✏️ Update Course
PATCH http://localhost:3000/courses/8cd014a1-c081-4ce5-8ea8-2c146e4c67a4
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  
  "published": true
}

###

### ❌ Delete Course
DELETE http://localhost:3000/courses/2a9aae4e-5a5b-4896-b8fd-c3c2fd9a63fb
Authorization: Bearer {{instructor_token}}

### Get course by category
GET http://localhost:3000/courses/category/Programming


###fetch all unique course categories
GET http://localhost:3000/courses/categories

### fetch courses in a specific category
GET http://localhost:3000/courses/category/:name 

### Delete all courses under a specific category
DELETE http://localhost:3000/courses/category/Biz
Authorization: Bearer {{admin_token}}
