### 🔐 Set your instructor token here
@instructor_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjhmYWFmNS1hMmMyLTRhNGQtYWE3YS02MWJmNmM3ZWVlMTIiLCJlbWFpbCI6Imluc3RydWN0b3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiSU5TVFJVQ1RPUiIsImlhdCI6MTc1MTkxOTg2MiwiZXhwIjoxNzUyMDA2MjYyfQ.RrySldNoBkXXuqNzg5euj4AAO3QnCdScvFJSJMAeLGI
@content_id = 044873fb-6bd7-4fbb-9221-ca07f1464433
@lesson_id = a0297ec1-e963-470b-ab7d-ede7c39ac879

### ✅ Create Lesson
POST http://localhost:3000/contents/{{content_id}}/lessons
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Topic 3",
  "type": "PDF",
  "contentUrl": "https://www.kanopystreaming.com/sites/default/files/learningspanish.pdf "
}

### 📄 Get All Lessons in a Module
GET http://localhost:3000/contents/{{content_id}}/lessons
Authorization: Bearer {{instructor_token}}

### ✏️ Update Lesson
PATCH http://localhost:3000/contents/{{content_id}}/lessons/{{lesson_id}}
Authorization: Bearer {{instructor_token}}
Content-Type: application/json

{
  "title": "Updated Lesson Title",
  "contentUrl": "https://example.com/updated.mp4"
}

### ❌ Delete Lesson
DELETE http://localhost:3000/contents/{{content_id}}/lessons/1d0a8f93-41d3-42b4-8929-4d878b7b6311
Authorization: Bearer {{instructor_token}}